import type { Officer, SiteStats } from "./types"

export const SEED_OFFICERS: Officer[] = [
  {
    id: "1",
    badgeNo: "#101",
    name: "Richye Smoke",
    rank: "Captain",
    unit: "High Command",
    status: "Görevde",
    seniorityMonths: 48,
    rankProgress: 100,
    nextRank: null,
    isCommand: true,
    stats: { dutyHours: 1240, patrols: 312, commendations: 18, warnings: 0 },
  },
  {
    id: "2",
    badgeNo: "#137",
    name: "Isaac Hancer",
    rank: "Captain",
    unit: "High Command",
    status: "Görevde",
    seniorityMonths: 38,
    rankProgress: 88,
    nextRank: null,
    isCommand: true,
    stats: { dutyHours: 980, patrols: 240, commendations: 14, warnings: 0 },
  },
  {
    id: "3",
    badgeNo: "#237",
    name: "Jon Nollane",
    rank: "Senior Lieutenant",
    unit: "High Command",
    status: "Görevde",
    seniorityMonths: 30,
    rankProgress: 72,
    nextRank: "Captain",
    isCommand: true,
    stats: { dutyHours: 820, patrols: 198, commendations: 11, warnings: 0 },
  },
  {
    id: "4",
    badgeNo: "#502",
    name: "Boris Harold",
    rank: "Senior Sergeant",
    unit: "Supervisor",
    status: "Görevde",
    seniorityMonths: 26,
    rankProgress: 65,
    nextRank: "Senior Lieutenant",
    isCommand: true,
    stats: { dutyHours: 740, patrols: 176, commendations: 9, warnings: 0 },
  },
  {
    id: "5",
    badgeNo: "#012",
    name: "A. Vasquez",
    rank: "Müfettiş",
    unit: "Polis",
    status: "Aktif",
    seniorityMonths: 20,
    rankProgress: 54,
    nextRank: "Başmüfettiş",
    stats: { dutyHours: 560, patrols: 134, commendations: 7, warnings: 1 },
  },
  {
    id: "6",
    badgeNo: "#018",
    name: "D. Novak",
    rank: "Başçavuş",
    unit: "Polis",
    status: "Görevde",
    seniorityMonths: 16,
    rankProgress: 42,
    nextRank: "Müfettiş",
    stats: { dutyHours: 420, patrols: 112, commendations: 5, warnings: 0 },
  },
  {
    id: "7",
    badgeNo: "#023",
    name: "L. Chen",
    rank: "Çavuş",
    unit: "Polis",
    status: "Aktif",
    seniorityMonths: 12,
    rankProgress: 35,
    nextRank: "Başçavuş",
    stats: { dutyHours: 310, patrols: 88, commendations: 4, warnings: 2 },
  },
  {
    id: "8",
    badgeNo: "#031",
    name: "P. Williams",
    rank: "Kıdemli Trooper",
    unit: "Polis",
    status: "İzinli",
    seniorityMonths: 9,
    rankProgress: 60,
    nextRank: "Çavuş",
    stats: { dutyHours: 240, patrols: 72, commendations: 3, warnings: 1 },
  },
  {
    id: "9",
    badgeNo: "#037",
    name: "K. Brooks",
    rank: "Trooper",
    unit: "Polis",
    status: "Görevde",
    seniorityMonths: 6,
    rankProgress: 45,
    nextRank: "Kıdemli Trooper",
    stats: { dutyHours: 180, patrols: 54, commendations: 2, warnings: 0 },
  },
  {
    id: "10",
    badgeNo: "#041",
    name: "E. Santos",
    rank: "Trooper",
    unit: "Polis",
    status: "Eğitimde",
    seniorityMonths: 4,
    rankProgress: 25,
    nextRank: "Kıdemli Trooper",
    stats: { dutyHours: 90, patrols: 28, commendations: 1, warnings: 0 },
  },
  {
    id: "11",
    badgeNo: "#048",
    name: "T. Reyes",
    rank: "Deneme Trooper",
    unit: "Polis",
    status: "Aktif",
    seniorityMonths: 2,
    rankProgress: 15,
    nextRank: "Trooper",
    stats: { dutyHours: 48, patrols: 14, commendations: 0, warnings: 1 },
  },
  {
    id: "12",
    badgeNo: "#055",
    name: "C. Morgan",
    rank: "Aday",
    unit: "Polis",
    status: "Eğitimde",
    seniorityMonths: 1,
    rankProgress: 8,
    nextRank: "Deneme Trooper",
    stats: { dutyHours: 12, patrols: 4, commendations: 0, warnings: 0 },
  },
]

export const SEED_STATS: SiteStats = {
  yearsActive: 3,
  totalPersonnel: 12,
  activeTroopers: 8,
  sectors: 6,
}

export const COMMAND_STAFF = SEED_OFFICERS.filter((o) => o.isCommand)
